# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_cpp2 <- function(x, y) {
    .Call('_RCITcpp_cov_cpp2', PACKAGE = 'RCITcpp', x, y)
}

normalise_cpp2 <- function(x) {
    .Call('_RCITcpp_normalise_cpp2', PACKAGE = 'RCITcpp', x)
}

make_rff_cpp <- function(x, w, sigma, b) {
    .Call('_RCITcpp_make_rff_cpp', PACKAGE = 'RCITcpp', x, w, sigma, b)
}

RIT_cpp <- function(x, y, median_x, median_y, w, b, return_ts = 0L, n_bs = 100) {
    .Call('_RCITcpp_RIT_cpp', PACKAGE = 'RCITcpp', x, y, median_x, median_y, w, b, return_ts, n_bs)
}

RCIT_cpp <- function(x, y, z, median_x, median_y, median_z, w, wy, wz, b, by, bz, return_ts = 0L, n_bs = 100) {
    .Call('_RCITcpp_RCIT_cpp', PACKAGE = 'RCITcpp', x, y, z, median_x, median_y, median_z, w, wy, wz, b, by, bz, return_ts, n_bs)
}

RCIT_disag_cpp <- function(x, y, z, median_x, median_y, median_z, w, wy, wz, b, by, bz, polygon_start_index, polygon_end_index, return_ts = 0L, n_bs = 100) {
    .Call('_RCITcpp_RCIT_disag_cpp', PACKAGE = 'RCITcpp', x, y, z, median_x, median_y, median_z, w, wy, wz, b, by, bz, polygon_start_index, polygon_end_index, return_ts, n_bs)
}

RIT_disag_cpp <- function(x, y, median_x, median_y, w, b, polygon_start_index, polygon_end_index, return_ts = 0L, n_bs = 100) {
    .Call('_RCITcpp_RIT_disag_cpp', PACKAGE = 'RCITcpp', x, y, median_x, median_y, w, b, polygon_start_index, polygon_end_index, return_ts, n_bs)
}

